version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: unlinked-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: unlinked
    volumes:
      - mongodb_data:/data/db
    networks:
      - unlinked-network

  # Backend API
  backend:
    build:
      context: ./backend
      target: development
    container_name: unlinked-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://admin:password@mongodb:27017/unlinked?authSource=admin
      - DATABASE_NAME=unlinked
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb
    networks:
      - unlinked-network

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      target: deps
    container_name: unlinked-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - unlinked-network
    command: npm run dev

volumes:
  mongodb_data:

networks:
  unlinked-network:
    driver: bridge 